image: golang:1.16

stages:
  - test
  - build

unit_tests:
  stage: test
  script:
    - make test

race_detector:
  stage: test
  script:
    - make race

lint_code:
  stage: test
  script:
    - go get golang.org/x/lint/golint
    - make lint

build:
  stage: build
  script:
    - make
